name: Basic Workflow Dispatch Example

on:
  workflow_dispatch:
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - run: echo "We did the thing!"
       - run: echo "Hey This is workflow_disptach trigger mannually"
       
